language: node_js
dist: trusty
sudo: required
node_js: 6
env:
  - PATH=$HOME/purescript:$PATH
install:
  - npm install
  - spago install
script:
  - npm run -s build
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
